project:
  type: website

website:
  page-navigation: true
  title: "James S. Norcross"
  description: "James S. Norcross' Professional Website"
  site-url: "https://www.linkedin.com/in/james-n-9034036/"
  
  page-footer:
    right: "Last page update: 2024"
    left: "&copy; Copyright 2024, James S. Norcross"
    
  navbar:
    right:
      - href: index.qmd
        text: Home 
      - href: about.qmd
        text: About Me
      - href: research.qmd
        text: Research Focus
      - text: Data Science Project
        menu: 
        - href: "#"  # Placeholder link
          text: Recent Data Science Project Proposal
        - href: "#"  # Placeholder link
          text: Complete Data Science Project
        - href: "#"  # Placeholder link
          text: Complete Data Science Project Presentation
      - href: cv.pdf
        text: Curriculum Vitae
      - text: Assignments
        menu:
        - href: "#"  # Placeholder link
          text: Comparison Review Article
        - href: "#"  # Placeholder link
          text: Figure01
        - href: "#"  # Placeholder link
          text: Assignment1
        - href: "#"  # Placeholder link
          text: Assignment2
        - href: "#"  # Placeholder link
          text: Assignment3
        - href: "#"  # Placeholder link
          text: Assignment4
        - href: "#"  # Placeholder link
          text: Assignment5
        - href: "#"  # Placeholder link
          text: Assignment6
        - href: "#"  # Placeholder link
          text: Assignment7
        - href: "#"  # Placeholder link
          text: Assignment8
        - text: Labs
        - href: "#"  # Placeholder link
          text: Lab01
        - href: "#"  # Placeholder link
          text: Lab02
        - href: "#"  # Placeholder link
          text: Lab03
       
format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: visual 

